# .github/workflows/your-workflow-name.yml

name: Build and deploy Node.js app to Azure Web App - app-002-gen10-step3-2-node-oshima4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: npm install and build
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
        run: |
          npm install
          npm run build --if-present

      # ★★★ 1. Azureへのログインステップを追加 ★★★
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # サービスプリンシパルの認証情報を使用

      # ★★★ 2. デプロイステップからは publish-profile を削除 ★★★
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-2-node-oshima4'
          slot-name: 'Production'
          package: .

      # ★★★ このステップも azure/login での認証を使用します ★★★
      - name: Set up startup command
        uses: azure/appservice-settings@v1
        with:
          app-name: 'app-002-gen10-step3-2-node-oshima4'
          startup-command: 'npx next start -p $PORT'
