# ワークフローの名前を、実際のアプリ名に合わせて統一
name: Build and deploy Node.js app to Azure Web App - app-002-gen10-step3-2-node-oshima4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
        run: |
          npm install
          npm run build --if-present

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-2-node-oshima4'
          slot-name: 'Production'
          package: .

      - name: Set up startup command
        uses: azure/appservice-settings@v1
        with:
          app-name: 'app-002-gen10-step3-2-node-oshima4'
          startup-command: 'npx next start -p $PORT'
